version: '3.8'

services:
  db:
    build:
      context: ./sql
    container_name: db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p@ssw0rd"
    volumes:
      - db_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TesteInlog;User Id=sa;Password=p@ssw0rd;TrustServerCertificate=True
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end/desafio-inlog
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  db_data:

